trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"

- script: |
   git checkout -b master
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin master 
